### ISSUE TITLE
training time cost

### ISSUE THREAD

**Issue by cvtower** [d-li14/mobilenetv2.pytorch#1]
Hi @d-li14 ,

Nice work and performance!
Would you please share the training cost here? e.g. GPU detail, training hours.
Since i have only 1080ti and seems like training imagenet from scratch will takes too much time.
Thanks very much!

**Comment by d-li14** [comment]
Typically, I trained on 4 x TITAN Xp, and the whole training process will converge within around 60 hours. As far as I know, 4x1080Ti will not take much longer than that.

**Comment by cvtower** [comment]
Hi @d-li14 ，

Got it!
Thanks very much for your kind help!
