### ISSUE TITLE
Validation Input size

### ISSUE THREAD

**Issue by akamaster** [d-li14/mobilenetv2.pytorch#13]
Would you please clarify what is the input size during the validation? From the code, as it is defined in function  get_pytorch_val_loader in the file utils/dataloaders.py, it seems validation input size is 224/0.875 = 256:
` transforms.Resize(int(input_size / 0.875))`
I believe in the paper, results are reported for the central crop of size 224x224, isn't it? So comparison is not straightforward. Can you please add the results on 224x224 crops?

**Comment by d-li14** [comment]
Notice the line below, `CenterCrop` is 224.
