### ISSUE TITLE
Embedding size

### ISSUE THREAD

**Issue by andreysher** [d-li14/mobilenetv2.pytorch#19]
Hello, I found one interesting thing: The last layers in your state_dicts have shape 1280. I think they should change shape according to width_mult, but all checkpoints have shape 1280.

name_of_layer, shape
conv.0.weight torch.Size([1280, 160, 1, 1])
conv.1.weight torch.Size([1280])
conv.1.bias torch.Size([1280])
conv.1.running_mean torch.Size([1280])
conv.1.running_var torch.Size([1280])
conv.1.num_batches_tracked torch.Size([])
classifier.weight torch.Size([1000, 1280])
classifier.bias torch.Size([1000])

**Comment by d-li14** [comment]
If `width_mult` < 1, the embedding size would not change.
