### ISSUE TITLE
训练参数

### ISSUE THREAD

**Issue by luuuyi** [d-li14/mobilenetv2.pytorch#3]
你好，能公布下你的训练参数么，按照脚本给出的用于训练ResNet的默认参数并不能很好的训练mobilenetv2，所以想参考下你的设置

**Comment by d-li14** [comment]
You can refer to the original [paper](https://arxiv.org/abs/1801.04381), the training details of lightweight MobileNet models can be totally different from ResNet family.

**Comment by luuuyi** [comment]
@d-li14 thanks
