### ISSUE TITLE
mobilenetv2_0.1-7d1d638a.pth can not be loaded.

### ISSUE THREAD

**Issue by Gasoonjia** [d-li14/mobilenetv2.pytorch#4]
Thank you for your great work!
However, some problems occur when I load mobilenetv2_0.1-7d1d638a.pth to your mobile net with width _mult = 0.1.
Could you tell me the width_mult I should set?

**Comment by d-li14** [comment]
I think modifying the `models/imagenet/mobilenetv2.py` to set all the channels 4-divisible will work. Notice that this extremely narrow model is not originally supported by TensorFlow https://github.com/tensorflow/models/tree/master/research/slim/nets/mobilenet. Actually I designed it by myself.
