### ISSUE TITLE
图像预处理

### ISSUE THREAD

**Issue by phoenares** [d-li14/mobilenetv2.pytorch#9]
请问下使用模型的话，图像该怎么预处理啊，均值，方差，还有RGB通道，谢谢

**Comment by d-li14** [comment]
refer to https://github.com/d-li14/mobilenetv2.pytorch/blob/master/imagenet.py#L197-L202, https://github.com/d-li14/mobilenetv2.pytorch/blob/master/imagenet.py#L214-L218

**Comment by phoenares** [comment]
> refer to https://github.com/d-li14/mobilenetv2.pytorch/blob/master/imagenet.py#L197-L202, https://github.com/d-li14/mobilenetv2.pytorch/blob/master/imagenet.py#L214-L218

好的，谢谢
